### PR TITLE
fix wrong file name

### PR DESCRIPTION
**Pull request by snowendless**
'dxBugIdConfig' to 'dxConfig.py'

I can not find dxBugIdConfig.py, let's fix it with dxConfig

### CODE REVIEW

**Comment by SkyLined** [comment]
Thank you for the report. I'll fix the incorrect name in an upcoming commit, however the other changes are not related to this request. Normally, I would ask you to submit a separate request for them, but I already added a command line switch (`-v`, `--verbose`) to implement what you want in a more recent version. However, as your pull request suggested, I've added a `dxConfig` setting that you can use to change this too (`dxConfig["bOutputCdbIO"]`), so you can use either `-v`, `--dxConfig.bOutputCdbIO=true`, or make this the default by changing `dxConfig.py`. I will commit this soon too.

**Comment by SkyLined** [comment]
`--verbose` and `bOutputCdbIO` have now been implemented:
https://github.com/SkyLined/BugId/commit/982005c5c29d687758fa67bfa039315dee0fa5c3

**Comment by snowendless** [comment]
Sorry for the noicy request, I'm pretty new of Github.

It's great to have the changes, I will test BugId more to make it better.



szg 
 
From: SkyLined
Date: 2017-07-17 19:52
To: SkyLined/BugId
CC: Song Zhiguang; Author
Subject: Re: [SkyLined/BugId] fix wrong file name (#36)
Thank you for the report. I'll fix the incorrect name in an upcoming commit, however the other changes are not related to this request. Normally, I would ask you to submit a separate request for them, but I already added a command line switch (-v, --verbose) to implement what you want in a more recent version. However, as your pull request suggested, I've added a dxConfig setting that you can use to change this too (dxConfig["bOutputCdbIO"]), so you can use either -v, --dxConfig.bOutputCdbIO=true, or make this the default by changing dxConfig.py. I will commit this soon too.

**Comment by SkyLined** [comment]
don't worry about not submitting bugs correctly too much: If much rather have a noisy bug report, than no bug report at all. Thanks for giving BugId a try, let me know if anything is unclear or broken and I will try to make it better.

**Pull request closed without merging**
